[package]
name = "my-project"
version = "0.1.0"
authors = ["runner"]
edition = "2021"


[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"


